// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waqrxzfhahvttybqcinb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhcXJ4emZoYWh2dHR5YnFjaW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwODU1ODgsImV4cCI6MjA1OTY2MTU4OH0.YjE_YvH4KmAbWQ0Ql-HBIy5tYxtuD_vWG-vVg4oPRXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);